export const BLOCKS = {
  AIR: 0,
  REGOLITH: 1,
  IRON_ORE: 2,
  SILICON_CRYSTAL: 3,
  TITANIUM_ORE: 4,
  ICE_BLOCK: 5,
  QUANTUM_CRYSTAL: 6,
  STEEL_BLOCK: 7,
  SOLAR_PANEL: 8,
  OXYGEN_GENERATOR: 9,
  REACTOR_CORE: 10,
  LAUNCH_PAD: 11,
  COMPUTER_BLOCK: 12,
};

export const BLOCK_DATA = {
  [BLOCKS.AIR]:              { name: 'Air',               solid: false, color: 0x000000, hardness: 0 },
  [BLOCKS.REGOLITH]:         { name: 'Regolith',          solid: true,  color: 0x8a7a6a, hardness: 1 },
  [BLOCKS.IRON_ORE]:         { name: 'Iron Ore',          solid: true,  color: 0x8b6f5e, hardness: 3 },
  [BLOCKS.SILICON_CRYSTAL]:  { name: 'Silicon Crystal',   solid: true,  color: 0x6090a0, hardness: 2 },
  [BLOCKS.TITANIUM_ORE]:     { name: 'Titanium Ore',      solid: true,  color: 0x7090b0, hardness: 4 },
  [BLOCKS.ICE_BLOCK]:        { name: 'Ice Block',         solid: true,  color: 0xa0d0f0, hardness: 1 },
  [BLOCKS.QUANTUM_CRYSTAL]:  { name: 'Quantum Crystal',   solid: true,  color: 0x8040ff, hardness: 5 },
  [BLOCKS.STEEL_BLOCK]:      { name: 'Steel Block',       solid: true,  color: 0x708090, hardness: 3 },
  [BLOCKS.SOLAR_PANEL]:      { name: 'Solar Panel',       solid: true,  color: 0x1040c0, hardness: 2 },
  [BLOCKS.OXYGEN_GENERATOR]: { name: 'Oxygen Generator',  solid: true,  color: 0x40a0ff, hardness: 3 },
  [BLOCKS.REACTOR_CORE]:     { name: 'Reactor Core',      solid: true,  color: 0xff6020, hardness: 5 },
  [BLOCKS.LAUNCH_PAD]:       { name: 'Launch Pad',        solid: true,  color: 0x505060, hardness: 4 },
  [BLOCKS.COMPUTER_BLOCK]:   { name: 'Computer Block',    solid: true,  color: 0x204060, hardness: 2 },
};
